### PR TITLE
KubernetesWatchTask.getWatchContext and KubernetesWatchTask.createWat…

### LINKED ISSUE #3054: KubernetesWatchTask.getWatchContext The declared Exception exception is never thrown
### Description

The method [KubernetesWatchTask.getWatchContext](https://github.com/eclipse-jkube/jkube/blob/f0ae12a58ffc0ec3874241169c419a25c7b886a7/gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/KubernetesWatchTask.java#L90) declares an Exception that is never thrown.

The following line
https://github.com/eclipse-jkube/jkube/blob/f0ae12a58ffc0ec3874241169c419a25c7b886a7/gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/KubernetesWatchTask.java#L90

- [x] should be changed to:
```java
  private WatchContext getWatchContext() {
```

### Before you start :red_circle:

:point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down::point_down::point_down::point_down::point_down::point_down::point_down:
Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first. Pay special attention to the ECA agreement section and the requirement to sign-off your commit.

#### Kubernetes

If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.

- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)

#### OpenShift

If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.

Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

### PR DESCRIPTION
**Pull request by kiratkumar47**
KubernetesWatchTask.getWatchContext The declared Exception is never thrown

## Description
Fixes #3054 

## Type of change
 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.dev/jkube/contributing)
 - [x] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [x] My code follows the style guidelines of this project
 - [x] I Keep It Small and Simple: The smaller the PR is, the easier it is to review and have it merged
 - [ ] I use [conventional commits](https://www.conventionalcommits.org/) in my commit messages
 - [x] I have performed a self-review of my code
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [x] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I have added tests that prove my fix is effective or that my feature works
 - [x] New and existing unit tests pass locally with my changes
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by manusa** [comment]
### Eclipse JKube [CI Report](https://github.com/eclipse-jkube/ci)

Started new GH workflow run for https://github.com/eclipse-jkube/jkube/pull/3077 (_2024-05-20T11:19:17Z_)

:gear: [JKube E2E Tests (9157889422)](https://github.com/eclipse-jkube/ci/actions/runs/9157889422) :hourglass_flowing_sand:
- :hourglass_flowing_sand: [Bootstrap CI test run (#3077)](https://github.com/eclipse-jkube/ci/actions/runs/9157889422/job/25175134584)

**Comment by kiratkumar47** [comment]
Hi @manusa,

This PR is ready for review. 
My initial commit was made using a different email, but I have recommitted the code using the email associated with my signed agreement. Please let me know if there is anything else I need to do.

**Comment by manusa** [comment]
You should have amended the original commit. The PR has now a commit from an invalid user, so it's still not possible to merge.

**Comment by kiratkumar47** [comment]
> You should have amended the original commit. The PR has now a commit from an invalid user, so it's still not possible to merge.

I have amended the original commit. Please check if this resolves the issue. I am new to this and would appreciate your help.

**Comment by manusa** [comment]
It doesn't, at this stage, I'd advise you to close the PR and start from scratch using a fresh version of the master branch.

**Pull request closed without merging**
