### PR TITLE
docs: Improve readability of Eclipse JKube plugin documentation titles

### PR DESCRIPTION
**Pull request by sunix**
## Description

Currently, the titles of our plugin documentation pages aren't sufficiently human-readable:

- the titles don't clearly indicate that they are for documentation
- while `org.eclipse.jkube/kubernetes-maven-plugin` is suitable in code, it's not as effective as a webpage title

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.dev/jkube/contributing)
 - [x] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [x] My code follows the style guidelines of this project
 - [x] I Keep It Small and Simple: The smaller the PR is, the easier it is to review and have it merged
 - [x] I use [conventional commits](https://www.conventionalcommits.org/) in my commit messages
 - [x] I have performed a self-review of my code
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I have added tests that prove my fix is effective or that my feature works
 - [ ] New and existing unit tests pass locally with my changes
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by manusa** [comment]
### Eclipse JKube [CI Report](https://github.com/jkubeio/ci)

Started new GH workflow run for https://github.com/eclipse/jkube/pull/2861 (_2024-03-28T15:12:21Z_)

:gear: [JKube E2E Tests (8469479577)](https://github.com/jkubeio/ci/actions/runs/8469479577) :hourglass_flowing_sand:
- :hourglass_flowing_sand: [Bootstrap CI test run (#2861)](https://github.com/jkubeio/ci/actions/runs/8469479577/job/23204907878)

**Comment by manusa** [comment]
This might break the website.
I recall there were some nasty hacks I had to do (https://github.com/jkubeio/jkube-website/blob/main/gatsby-node.js) on several places. Please make sure to check everything works out with these changes: https://github.com/jkubeio/jkube-website/blob/629282c23faa6126545b2a8292d9a54fbf92e305/gatsby-config.js#L31

**Comment by sunix** [comment]
> This might break the website.
> I recall there were some nasty hacks I had to do (https://github.com/jkubeio/jkube-website/blob/main/gatsby-node.js) on several places. Please make sure to check everything works out with these changes: https://github.com/jkubeio/jkube-website/blob/629282c23faa6126545b2a8292d9a54fbf92e305/gatsby-config.js#L31

yes it is breaking the website :/

**Comment by sunix** [comment]
still, I am unsure of the impact of https://github.com/jkubeio/jkube-website/blob/main/gatsby-node.js#L36

```
const duplicateAsciiNodes = ({node, actions: {createNode}, createNodeId, createContentDigest}) => {
  if (node.internal.type === 'Asciidoc' && isValidNode(node)) {
    const duplicateAsciiNode = {...node,
      id: createNodeId(`${node.id}-${node.document.title}`),
      parent: null,
      internal: {
        type: 'AsciidocCopy',
        mediaType: 'text/html'
      }
    };
    duplicateAsciiNode.internal.contentDigest = createContentDigest(duplicateAsciiNode);
    createNode(duplicateAsciiNode);
  }
};

```

**Review by rohanKanojia — APPROVED** [review]

**Comment by sunix** [comment]
TODO: check if all the plugin documentation are well generated

**Comment by sunix** [comment]
I tested locally and it seems to work
https://github.com/eclipse-jkube/jkube-website/pull/87 + this PR, generated to https://longing-blood.surge.sh/jkube/docs/

**Review by manusa — APPROVED** [review]
LGTM, thx!

**Pull request merged**
