### PR TITLE
SerializationTest is failing #3113

### LINKED ISSUE #3113: SerializationTest is failing on windows
Part of #1338 

SerializationTest is failing after the latest commits.

[ERROR] Failures:
[ERROR]   SerializationTest$MultiLineStringsSerializedToScalarYamlBlocks.whenStringEndingWithNewline_thenAddBlockIndicatorInSerializedObject:240

I would like to be assigned for the issue since I have already done some research.

### PR DESCRIPTION
**Pull request by Sintivrousai**
## Description

Fixes #3113

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [ ] I have read the [contributing guidelines](https://www.eclipse.dev/jkube/contributing)
 - [ ] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [ ] My code follows the style guidelines of this project
 - [ ] I Keep It Small and Simple: The smaller the PR is, the easier it is to review and have it merged
 - [ ] I use [conventional commits](https://www.conventionalcommits.org/) in my commit messages
 - [ ] I have performed a self-review of my code
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I have added tests that prove my fix is effective or that my feature works
 - [ ] New and existing unit tests pass locally with my changes
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by manusa** [comment]
### Eclipse JKube [CI Report](https://github.com/eclipse-jkube/ci)

Started new GH workflow run for https://github.com/eclipse-jkube/jkube/pull/3115 (_2024-05-30T07:40:03Z_)

:gear: [JKube E2E Tests (9298843945)](https://github.com/eclipse-jkube/ci/actions/runs/9298843945) :hourglass_flowing_sand:
- :hourglass_flowing_sand: [Bootstrap CI test run (#3115)](https://github.com/eclipse-jkube/ci/actions/runs/9298843945/job/25591514414)

**Review by rohanKanojia — APPROVED** [review]

**Comment by rohanKanojia** [comment]
I tested it on a [GitHub actions pipeline](https://github.com/rohankanojia-forks/jkube-build-testing/actions/runs/9299557228/job/25593714543), test is passing wit these changes

**Comment by rohanKanojia** [comment]
@Sintivrousai : Thanks for creating PR! I see another test failing in HelmServiceTest in [windows github action pipeline](https://github.com/rohankanojia-forks/jkube-build-testing/actions/runs/9299557228/job/25593714543). Could you please create an issue about this as well?

**Comment by Sintivrousai** [comment]
> @Sintivrousai : Thanks for creating PR! I see another test failing in HelmServiceTest in [windows github action pipeline](https://github.com/rohankanojia-forks/jkube-build-testing/actions/runs/9299557228/job/25593714543). Could you please create an issue about this as well?

Yes of course I'm encountering this error too.

**Comment by rohanKanojia** [comment]
@Sintivrousai : I see, I've added a code pointer in the issue. Please try it out to see if it fixes the issue

**Review by manusa — APPROVED** [review]
LGTM, thx!

**Pull request merged**
