### PR TITLE
: Refactor PortForwardService to Replace Anonymous Thread with Lambda

### LINKED ISSUE #3285: PortForwardService : Anonymous `new Thread()` can be replaced with `new Thread(() -> {…}) `
### Component

JKube Kit

### Description
This anonymous class can be replaced with `new Thread()` call receiving a lambda: 

https://github.com/eclipse-jkube/jkube/blob/e1cde0bd0d4ab1a659db7b1f7a884705048b27de/jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/PortForwardService.java#L172-L178

### Expected Behavior
Anonymous class is replaced with lambda

### Acceptance Criteria
- [x] Anonymous class is replaced with lambda in PortForwardService
- [x] PortForwardServiceTest is passing after making this change

### PR DESCRIPTION
**Pull request by Er-Sadiq**
Fixes #3285

Changes Made:

Replaced the anonymous inner class in the Runtime.getRuntime().addShutdownHook method with a lambda expression.

### CODE REVIEW

**Comment by manusa** [comment]
### Eclipse JKube [CI Report](https://github.com/eclipse-jkube/ci)

Started new GH workflow run for https://github.com/eclipse-jkube/jkube/pull/3300 (_2024-08-03T10:44:38Z_)

:gear: [JKube E2E Tests (10227408894)](https://github.com/eclipse-jkube/ci/actions/runs/10227408894) :hourglass_flowing_sand:
- :hourglass_flowing_sand: [Bootstrap CI test run (#3300)](https://github.com/eclipse-jkube/ci/actions/runs/10227408894/job/28298819552)

**Comment by rohanKanojia** [comment]
@Er-Sadiq : 
Welcome, Thanks a lot for contributing to Eclipse JKube :+1:,

In order to contribute to Eclipse, you would need to create an [Eclipse Account](https://accounts.eclipse.org/) and Sign [Eclipse Contributor Agreement](https://accounts.eclipse.org/user/login?destination=user/eca). Once you've created an eclipse account you would need to update your commit message with a `Signed-off-by:` footer. You can do it like this:
```
# (Optional): Configure Git User and Email
git config user.name "Your Name"
git config user.email "your_email@example.com"

# Amend your previous commit with signed off footer
git commit --amend --signoff

# push changes again
git push origin yourbranchname -f
```

**Comment by Er-Sadiq** [comment]
@rohanKanojia Hi , I have amended my commit and have signed the ECA . if all is good kindly accept my PR

**Review by manusa — APPROVED** [review]
LGTM, thx!

**Review by rohanKanojia — APPROVED** [review]

**Comment by rohanKanojia** [comment]
@Er-Sadiq : Please link issue number in your pull request description like this:

```
Fix #3285
```

**Comment by Er-Sadiq** [comment]
@rohanKanojia i've mentioned it at the top

**Pull request merged**
