### PR TITLE
Explicit Type Argument Replaced with <>

### LINKED ISSUE #3368: GradleUtil: Explicit type argument Configuration can be replaced with <>
### Description

The class [GradleUtil](https://github.com/eclipse-jkube/jkube/blob/edd44d90d52a013f33d22cd38f682b59facef53b/gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/GradleUtil.java#L117) presents the issue: Explicit type argument Configuration can be replaced with <>.

The following line:
https://github.com/eclipse-jkube/jkube/blob/edd44d90d52a013f33d22cd38f682b59facef53b/gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/GradleUtil.java#L117
should be changed to:

```java
    return new ArrayList<>(gradleProject.getConfigurations()).stream()
```
### :red_circle: Before you start :red_circle:

:point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down:

Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first.

Pay special attention to the ECA agreement section and the requirement to sign-off your commit.

This is a [first-timers-only](https://eclipse.dev/jkube/contributing/#first-timers-only-issues) issue. These issues are especially created for contributors who are contributing to the project for the **first time**.

If you have already contributed to this project in the past, please don't ask to be assigned one of these issues and look for [good-first-issues](https://github.com/eclipse-jkube/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22) or [help-wanted](https://github.com/eclipse-jkube/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22help+wanted%22+) issues instead in order to continue you contributor journey in the project.

### PR DESCRIPTION
**Pull request by pujakarakoti07**
## Description

Fixes #3368

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.dev/jkube/contributing)
 - [x] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [x] My code follows the style guidelines of this project
 - [x] I Keep It Small and Simple: The smaller the PR is, the easier it is to review and have it merged
 - [x] I use [conventional commits](https://www.conventionalcommits.org/) in my commit messages
 - [x] I have performed a self-review of my code
 - [x] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [x] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [x] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [x] I have added tests that prove my fix is effective or that my feature works
 - [x] New and existing unit tests pass locally with my changes
 - [x] I tested my code in Kubernetes
 - [x] I tested my code in OpenShift

### CODE REVIEW

**Comment by manusa** [comment]
### Eclipse JKube [CI Report](https://github.com/eclipse-jkube/ci)

Started new GH workflow run for https://github.com/eclipse-jkube/jkube/pull/3385 (_2024-09-17T12:51:54Z_)

:gear: [JKube E2E Tests (10903429575)](https://github.com/eclipse-jkube/ci/actions/runs/10903429575) :hourglass_flowing_sand:
- :hourglass_flowing_sand: [Bootstrap CI test run (#3385)](https://github.com/eclipse-jkube/ci/actions/runs/10903429575/job/30257489276)

**Comment by pujakarakoti07** [comment]
Done please check.

**Comment by manusa** [comment]
Hi @pujakarakoti07 

Welcome, thanks a lot for contributing to Eclipse JKube :+1:!

In order to contribute to Eclipse, you need to create an [Eclipse Account](https://accounts.eclipse.org/) and sign the [Eclipse Contributor Agreement](https://accounts.eclipse.org/user/login?destination=user/eca). Once you've created the Eclipse account you have to update your commit message with a `Signed-off-by:` footer. You can do it like this:
```
# (Optional): Configure Git User and Email
git config user.name "Your Name"
git config user.email "your_email@example.com"

# Amend your previous commit with signed off footer
git commit --amend --signoff

# push changes again
git push origin yourbranchname -f
```

**Comment by manusa** [comment]
The email you used in your git configuration is not the one you used to sign the ECA.
It looks like there is a typo and you've appended an extra zero:
image

**Comment by pujakarakoti07** [comment]
Changed email.

**Comment by manusa** [comment]
> Changed email.

Still not passing: https://api.eclipse.org/git/eca/status/gh/eclipse-jkube/jkube/3385

The valid email is the one that **doesn't** have `30@` but has `3@`.
Make sure that the commit author and the Signed-off-by footer refer to the latter email account only.

**Comment by rohanKanojia** [comment]
@pujakarakoti07 : Could you please clean up `Signed-Off By:` lines in your commit message? You're supposed to keep only one which contains correct email address?

1. `git commit --amend`
2. Clean up `Signed-Off By:` lines from commit message
3. Make sure that there is only one `Signed-Off By:` footer in your commit message and it points to email you used while signing ECA.
4. Force push to your branch `git push origin <your-branch-name>`

**Pull request closed without merging**
