### PR TITLE
Fix #3285

### LINKED ISSUE #3285: PortForwardService : Anonymous `new Thread()` can be replaced with `new Thread(() -> {…}) `
### Component

JKube Kit

### Description
This anonymous class can be replaced with `new Thread()` call receiving a lambda: 

https://github.com/eclipse-jkube/jkube/blob/e1cde0bd0d4ab1a659db7b1f7a884705048b27de/jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/PortForwardService.java#L172-L178

### Expected Behavior
Anonymous class is replaced with lambda

### Acceptance Criteria
- [x] Anonymous class is replaced with lambda in PortForwardService
- [x] PortForwardServiceTest is passing after making this change

### PR DESCRIPTION
**Pull request by yyd0**
## Description

Fixes # (3285)

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [ ] I have read the [contributing guidelines](https://www.eclipse.dev/jkube/contributing)
 - [ ] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [ ] My code follows the style guidelines of this project
 - [ ] I Keep It Small and Simple: The smaller the PR is, the easier it is to review and have it merged
 - [ ] I use [conventional commits](https://www.conventionalcommits.org/) in my commit messages
 - [ ] I have performed a self-review of my code
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I have added tests that prove my fix is effective or that my feature works
 - [ ] New and existing unit tests pass locally with my changes
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by manusa** [comment]
### Eclipse JKube [CI Report](https://github.com/eclipse-jkube/ci)

Started new GH workflow run for https://github.com/eclipse-jkube/jkube/pull/3292 (_2024-08-01T06:25:57Z_)

:gear: [JKube E2E Tests (10193194503)](https://github.com/eclipse-jkube/ci/actions/runs/10193194503) :hourglass_flowing_sand:
- :hourglass_flowing_sand: [Bootstrap CI test run (#3292)](https://github.com/eclipse-jkube/ci/actions/runs/10193194503/job/28197370350)

**Comment by rohanKanojia** [comment]
@yyd0 : Could you please link issue in your PR description like this?

```
Fix #3285
```

**Comment by rohanKanojia** [comment]
@yyd0 : Could you please comment on #3285 so that I can assign the issue to you?

**Comment by rohanKanojia** [comment]
@yyd0 : Hello ECA check is still failing. Could you please verify whether you're using the correct email address  from which you created Eclipse Account?

**Pull request closed without merging**
