### PR TITLE
chore (jkube-kit/common) : Remove workaround added for Fabric8 Kubernetes Mock Server empty context

### LINKED ISSUE #3185: Remove workaround from KubernetesMockServerUtil once issue is fixed in KubernetesMockServer
### Component

JKube Kit

### Description

We have added this workaround in a utility class to work around https://github.com/fabric8io/kubernetes-client/issues/6068 

https://github.com/eclipse-jkube/jkube/blob/4da625ec8a3854c1480127d622b320b56ea4ba92/jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/KubernetesMockServerUtil.java#L29

There is already a pull request in KubernetesClient to fix this issue https://github.com/fabric8io/kubernetes-client/pull/6069 . 

Once we get this merged and upgrade to the fixed version of Fabric8 KubernetesClient . Remove this utility method as it's doing the same thing that would be fixed upstream.

### Expected Behavior
Outlined method is removed once issue is fixed in KubernetesClient project

### Acceptance Criteria
- [ ] exportKubernetesClientConfigToFile is removed once we upgrade to next version of KubernetesClient that contains the fix

### PR DESCRIPTION
**Pull request by rohanKanojia**
## Description

Fix #3185 

https://github.com/fabric8io/kubernetes-client/issues/6068 has been fixed and we've upgraded to KubernetesClient v6.13.1 which already contains fix for the abovementioned issue.

We don't need to have this method anymore.

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.dev/jkube/contributing)
 - [x] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [x] My code follows the style guidelines of this project
 - [x] I Keep It Small and Simple: The smaller the PR is, the easier it is to review and have it merged
 - [x] I use [conventional commits](https://www.conventionalcommits.org/) in my commit messages
 - [x] I have performed a self-review of my code
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I have added tests that prove my fix is effective or that my feature works
 - [x] New and existing unit tests pass locally with my changes
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by manusa** [comment]
### Eclipse JKube [CI Report](https://github.com/eclipse-jkube/ci)

Started new GH workflow run for https://github.com/eclipse-jkube/jkube/pull/3223 (_2024-07-11T11:19:42Z_)

:gear: [JKube E2E Tests (9890477536)](https://github.com/eclipse-jkube/ci/actions/runs/9890477536) :hourglass_flowing_sand:
- :hourglass_flowing_sand: [Bootstrap CI test run (#3223)](https://github.com/eclipse-jkube/ci/actions/runs/9890477536/job/27318806918)

**Comment by manusa** [comment]
Is this fixing #3185?

**Comment by rohanKanojia** [comment]
@manusa : yes, you're right.

**Review by manusa — APPROVED** [review]
LGTM, thx!

**Pull request merged**
