### PR TITLE
Add abstract class for helm task

### LINKED ISSUE #2773: Align Gradle plugin behavior with that what is introduced by PR 2714 in the Maven plugin
### Component

Kubernetes Gradle Plugin

### Is your enhancement related to a problem? Please describe

@manusa opted this in https://github.com/eclipse/jkube/pull/2714#discussion_r1512130966, but I'm not a Gradle user, so I don't feel like I'm the right person to do so.
@rohanKanojia [asked to create an issue instead](https://github.com/eclipse/jkube/pull/2714#issuecomment-1980898152), so here I am 😀

Basically, PR 2714 introduces an abstract class for all Helm goals. Before the PR was merged, the class `HelmMojo` served as both a base class for `HelmLintMojo` and `HelmPushMojo` _and_ as a Maven goal in itself. After the PR was merged, the `AbstractHelmMojo` class is the base class and the `HelmMojo` class is just the Maven goal.

### Describe the solution you'd like

A base class for Helm goals in the Gradle plugin.

### PR DESCRIPTION
**Pull request by clarenced**
## Description

Based on the previous work done on the issue #2714 , we introduce the same Abstract class but for Gradle plugin. 
Fixes #2773

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [x] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.dev/jkube/contributing)
 - [x] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [x] My code follows the style guidelines of this project
 - [x] I Keep It Small and Simple: The smaller the PR is, the easier it is to review and have it merged
 - [x] I use [conventional commits](https://www.conventionalcommits.org/) in my commit messages
 - [x] I have performed a self-review of my code
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [x] I have added tests that prove my fix is effective or that my feature works
 - [ ] New and existing unit tests pass locally with my changes
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by manusa** [comment]
### Eclipse JKube [CI Report](https://github.com/eclipse-jkube/ci)

Started new GH workflow run for https://github.com/eclipse-jkube/jkube/pull/3166 (_2024-06-15T06:56:04Z_)

:gear: [JKube E2E Tests (9526290141)](https://github.com/eclipse-jkube/ci/actions/runs/9526290141) :hourglass_flowing_sand:
- :hourglass_flowing_sand: [Bootstrap CI test run (#3166)](https://github.com/eclipse-jkube/ci/actions/runs/9526290141/job/26261500566)

**Comment by clarenced** [comment]
Hi @manusa I have a problem with the license check. it could not verified the license for those dependencies. 

```
[main] INFO License information could not be automatically verified for the following content:
[main] INFO 
[main] INFO maven/mavencentral/com.github.java-json-tools/btf/1.3
[main] INFO maven/mavencentral/com.github.java-json-tools/jackson-coreutils/2.0
[main] INFO maven/mavencentral/com.github.java-json-tools/json-schema-core/1.2.14
[main] INFO maven/mavencentral/com.github.java-json-tools/msg-simple/1.2
[main] INFO maven/mavencentral/com.github.java-json-tools/uri-template/0.10
[main] INFO 
[main] INFO This content is either not correctly mapped by the system, or requires review.
```

Any idea how can I fixed this problem.

**Comment by manusa** [comment]
Yes, this is OK. These licenses are currently being vetted by the Eclipse Foundation legal IP team.

**Comment by rohanKanojia** [comment]
@clarenced : Looks good to me, Could you please address these [sonar code smells](https://sonarcloud.io/project/issues?id=jkubeio_jkube&pullRequest=3166&resolved=false&sinceLeakPeriod=true)?

**Review by rohanKanojia — APPROVED** [review]

**Review by manusa — APPROVED** [review]
LGTM, thx!

**Pull request merged**
