### PR TITLE
replace deprecated org.apache.commons.io.input.CountingInputStream with org.apache.commons.io.input.BoundedInputStream

### LINKED ISSUE #3029: OCIRegistryClient : Replace deprecated `org.apache.commons.io.input.CountingInputStream` with `org.apache.commons.io.input.BoundedInputStream`
### Component

JKube Kit

### Description

We're using CountingInputStream for pushing helm charts to OCI registries:

https://github.com/eclipse-jkube/jkube/blob/7d08fb086e056e60a7b5ac4533d4bc3a2bdcf09f/jkube-kit/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/oci/OCIManifestLayer.java#L37

In recent releases of Apache commons io, this class has been marked as `@Deprecated` (see [javadoc](https://commons.apache.org/proper/commons-io/apidocs/org/apache/commons/io/input/CountingInputStream.html)). We should replace this with the suggested alternative.

After making changes, we also need to verify that the functionality is also working as expected. For that you'll need to generate a helm chart and push it to some OCI registry (DockerHub, Quay, GitHub Container Registry etc). You can watch this demo video to get idea of workflow : :tv: [Sprint 244 - Eclipse JKube: Helm push to OCI repository](https://youtu.be/0R-ERhXiUTA)

### Expected Behavior
`CountingInputStream` is replaced with suggested alternative in [JavaDoc](https://commons.apache.org/proper/commons-io/apidocs/org/apache/commons/io/input/CountingInputStream.html)

### Acceptance Criteria
- [ ] `CountingInputStream` is replaced with `BoundedInputStream`
- [ ] Project compiles cleanly after making changes
- [ ] Helm Chart Push functionality is working after making changes

### PR DESCRIPTION
**Pull request by rohit-satya**
## Description

Fixes #3029

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.dev/jkube/contributing)
 - [x] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [x] My code follows the style guidelines of this project
 - [x] I Keep It Small and Simple: The smaller the PR is, the easier it is to review and have it merged
 - [x] I use [conventional commits](https://www.conventionalcommits.org/) in my commit messages
 - [x] I have performed a self-review of my code
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [x] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I have added tests that prove my fix is effective or that my feature works
 - [ ] New and existing unit tests pass locally with my changes
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by manusa** [comment]
### Eclipse JKube [CI Report](https://github.com/eclipse-jkube/ci)

Started new GH workflow run for https://github.com/eclipse-jkube/jkube/pull/3044 (_2024-05-11T15:58:18Z_)

:gear: [JKube E2E Tests (9044824739)](https://github.com/eclipse-jkube/ci/actions/runs/9044824739) :hourglass_flowing_sand:
- :hourglass_flowing_sand: [Bootstrap CI test run (#3044)](https://github.com/eclipse-jkube/ci/actions/runs/9044824739/job/24853894879)

**Comment by rohanKanojia** [comment]
@rohit-satya : Did you verify that Helm Chart Push functionality is working as expected?

**Comment by rohanKanojia** [comment]
@rohit-satya : You're right. I think we can use `BoundedInputStream.builder()` here instead.

**Comment by rohit-satya** [comment]
@rohanKanojia Makes sense, will make the change and check how to verify Helm Chart Push functionality

**Comment by rohit-satya** [comment]
@rohanKanojia I have made the required code changes, I will need some time to verify Helm Chart Push functionality.

**Comment by rohanKanojia** [comment]
@rohit-satya : Did you get any time to test this PR? I can see you're creating other PRs but there isn't any update on this one. Please try to complete a single task before moving on to the next one.

**Comment by rohit-satya** [comment]
@rohanKanojia I will be working on testing this PR next as I didn't have the setup to test.

**Comment by sunix** [comment]
@rohit-satya could you elaborate what you did try and where you are stuck ?

**Pull request closed without merging**
