### PR TITLE
Replaced Deprected  AsList method with AsertJ's method in `SimpleDockerFileUtilTest`

### LINKED ISSUE #3441: SimpleDockerfileUtilTest : Replace AssertJ's deprecated `asList()` DSL method with `asInstanceOf(InstanceOfAssertFactories.list(type.class))`
### Component

JKube Kit

### Task description

In the latest versions of Assertj `asList()` DSL method has been marked as deprecated:

https://github.com/eclipse-jkube/jkube/blob/e4af3d3ae2ab429c7c3af725e46482220902fc25/jkube-kit/generator/dockerfile-simple/src/test/java/org/eclipse/jkube/generator/dockerfile/simple/SimpleDockerfileUtilTest.java#L98

users are advised to use `asInstanceOf(InstanceOfAssertFactories.list(type.class))` instead, we need to update `asList()` calls with this. 

### Expected Behavior
AssertJ's `asList()` is replaced with `asInstanceOf(InstanceOfAssertFactories.list(type.class))`

### Acceptance Criteria
- [x] `asList()` DSL method call is replaced with  `asInstanceOf(InstanceOfAssertFactories.list(type.class))` in all places

### PR DESCRIPTION
**Pull request by ShivamChavan01**
## Description

Replaced `asList()` with `asInstanceOf(InstanceOfAssertFactories.list(Type.class))` in `SimpleDockerFileUtilTest`
Fixes #3441 

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.dev/jkube/contributing)
 - [x] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [x] My code follows the style guidelines of this project
 - [x] I Keep It Small and Simple: The smaller the PR is, the easier it is to review and have it merged
 - [x] I use [conventional commits](https://www.conventionalcommits.org/) in my commit messages
 - [x] I have performed a self-review of my code
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I have added tests that prove my fix is effective or that my feature works
 - [ ] New and existing unit tests pass locally with my changes
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by manusa** [comment]
### Eclipse JKube [CI Report](https://github.com/eclipse-jkube/ci)

Started new GH workflow run for https://github.com/eclipse-jkube/jkube/pull/3448 (_2024-10-10T07:17:59Z_)

:gear: [JKube E2E Tests (11269275004)](https://github.com/eclipse-jkube/ci/actions/runs/11269275004) :hourglass_flowing_sand:
- :hourglass_flowing_sand: [Bootstrap CI test run (#3448)](https://github.com/eclipse-jkube/ci/actions/runs/11269275004/job/31337567796)

**Review by rohanKanojia — APPROVED** [review]

**Comment by ShivamChavan01** [comment]
Hey @rohanKanojia Sorry My commit message has a Typo   Can i Change idk  how it happened

**Comment by manusa** [comment]
> Hey @rohanKanojia Sorry My commit message has a Typo Can i Change idk how it happened

Don't worry, it'll be changed once I squash the PR

**Review by manusa — APPROVED** [review]
LGTM, thx!

**Comment by rohanKanojia** [comment]
@ShivamChavan01 : You can use `git commit --amend` to change typos in your commit message (for future PRs)

**Pull request merged**
