### PR TITLE
feat: provide a way to set labels on images defined by Generators (#2…

### LINKED ISSUE #2885: Provide a way to set labels on images defined by Generators
### Component

Kubernetes Maven Plugin

### Is your enhancement related to a problem? Please describe

I miss a way to set labels on the container image when I build it through _generators_ (instead of the _images_ config). I use the spring-boot generator, but I suppose the issue is common to others.

### Describe the solution you'd like

I'd like to add a labels entry to the generator config, such as
```pom.xml
...
<generator>
  <config>
    <spring-boot>
      <color>always</color>
      <from>...</from>
      <labels>foo=abc,bar=123</labels><!-- with a CSV or nested elems -->
    </spring-boot>
  </config>
</generator>
...
```
Probably a comma separated list of values would resemble what already happens for _jkube.generator.tags_.

### Describe alternatives you've considered

Using _images_ tag or _dockerfile_ I would loose the support for automatic detection of layered jars

### Additional context

Discussed at https://github.com/eclipse/jkube/discussions/2884

### PR DESCRIPTION
**Pull request by davidecavestro**
## Description

Fixes #2885 providing a way to set labels on images defined by Generators

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [x] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.dev/jkube/contributing)
 - [x] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [x] My code follows the style guidelines of this project
 - [x] I Keep It Small and Simple: The smaller the PR is, the easier it is to review and have it merged
 - [x] I use [conventional commits](https://www.conventionalcommits.org/) in my commit messages
 - [ ] I have performed a self-review of my code
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [x] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [x] I have added tests that prove my fix is effective or that my feature works
 - [x] New and existing unit tests pass locally with my changes
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by manusa** [comment]
### Eclipse JKube [CI Report](https://github.com/eclipse-jkube/ci)

Started new GH workflow run for https://github.com/eclipse-jkube/jkube/pull/2956 (_2024-04-23T13:26:44Z_)

:gear: [JKube E2E Tests (8801272652)](https://github.com/eclipse-jkube/ci/actions/runs/8801272652) :hourglass_flowing_sand:
- :hourglass_flowing_sand: [Bootstrap CI test run (#2956)](https://github.com/eclipse-jkube/ci/actions/runs/8801272652/job/24154218671)

**Review by rohanKanojia — APPROVED** [review]

**Comment by rohanKanojia** [comment]
In my opinion, this is good enough to get started, we can iterate over this for more complex scenarios if needed.

**Comment by rohanKanojia** [comment]
@davidecavestro : Could you please add a line to [CHANGELOG.md](https://github.com/eclipse-jkube/jkube/blob/master/CHANGELOG.md) regarding this change?

**Comment by manusa** [comment]
Hi @davidecavestro, it seems that you haven't signed the ECA contributor agreement.
We can't merge this PR unless the paperwork is complete.
https://eclipse.dev/jkube/contributing/

**Review by manusa — APPROVED** [review]
LGTM, thx!

**Pull request merged**
