### PR TITLE
chore: replaced .length() with .isEmpty() for filenameTypes check in MappingConfig

### LINKED ISSUE #3233: MappingConfig 'filenameTypes.length() > 0' can be replaced with '!filenameTypes.isEmpty()'
### Description

The call to `List.size` can be replaced with `isEmpty` in [MappingConfig](https://github.com/eclipse-jkube/jkube/blob/5da6068d7756784aef9569568ee80f98da97e296/jkube-kit/config/resource/src/main/java/org/eclipse/jkube/kit/config/resource/MappingConfig.java).

The following line:
https://github.com/eclipse-jkube/jkube/blob/5da6068d7756784aef9569568ee80f98da97e296/jkube-kit/config/resource/src/main/java/org/eclipse/jkube/kit/config/resource/MappingConfig.java#L41

should be changed to:

```java
        return kind != null && filenameTypes != null && !filenameTypes.isEmpty();
```

### :red_circle: Before you start :red_circle:

:point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down:

Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first.

Pay special attention to the ECA agreement section and the requirement to sign-off your commit.

This is a [first-timers-only](https://eclipse.dev/jkube/contributing/#first-timers-only-issues) issue. These issues are especially created for contributors who are contributing to the project for the **first time**.

If you have already contributed to this project in the past, please don't ask to be assigned one of these issues and look for [good-first-issues](https://github.com/eclipse-jkube/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22) or [help-wanted](https://github.com/eclipse-jkube/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22help+wanted%22+) issues instead in order to continue you contributor journey in the project.

### PR DESCRIPTION
**Pull request by jesslane94**
## Description
Fixes #3233
FYI, looks like some of the whitespace got changed, let me know if this is something the linter shouldn't be doing.

## Type of change
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.dev/jkube/contributing)
 - [ ] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [x] My code follows the style guidelines of this project
 - [x] I Keep It Small and Simple: The smaller the PR is, the easier it is to review and have it merged
 - [x] I use [conventional commits](https://www.conventionalcommits.org/) in my commit messages
 - [x] I have performed a self-review of my code
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [x] I have added tests that prove my fix is effective or that my feature works
 - [ ] New and existing unit tests pass locally with my changes
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by manusa** [comment]
### Eclipse JKube [CI Report](https://github.com/eclipse-jkube/ci)

Started new GH workflow run for https://github.com/eclipse-jkube/jkube/pull/3256 (_2024-07-23T23:22:50Z_)

:gear: [JKube E2E Tests (10067767100)](https://github.com/eclipse-jkube/ci/actions/runs/10067767100) :hourglass_flowing_sand:
- :hourglass_flowing_sand: [Bootstrap CI test run (#3256)](https://github.com/eclipse-jkube/ci/actions/runs/10067767100/job/27831874243)

**Review by rohanKanojia — APPROVED** [review]

**Comment by rohanKanojia** [comment]
@jesslane94 : Thanks for adding a unit test! Looks good to me.

> FYI, looks like some of the whitespace got changed, let me know if this is something the linter shouldn't be doing.

Did you [configure your IDE to use Eclipse Code Formatter](https://eclipse.dev/jkube/contributing/#ide-config-and-code-style) as mentioned in the contributing guide? Are these added after IDE configuraiton

**Comment by jesslane94** [comment]
Ohhh, I will have to look into setting that up. I actually use VS Code, so I think it used whatever I have as default once I saved the file. I will look into how to make it follow the Eclipse rules since I think you only have instructions for the Eclipse and IntelliJ IDEs! Thanks again! :]

**Review by manusa — APPROVED** [review]
LGTM, thx!

**Pull request merged**
