### PR TITLE
fix: remove getter methods and use lombok @Getter in HelmConfig.HelmType

### LINKED ISSUE #2930: `HelmConfig.HelmType` may use lombok `@Getter`
### Component

JKube Kit

### Description

This class has explicit getters that can easily be replaced by using [Lombok's `@Getter` ](https://projectlombok.org/features/GetterSetter)annotation.

https://github.com/eclipse/jkube/blob/6ca26cdce98a073654be777d283f55215e6a1fbf/jkube-kit/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/HelmConfig.java#L93-L115

### Expected Behavior
Getter methods are removed and `@Getter` annotation is used

### Acceptance Criteria
- [ ] `@Getter` annotation is used in place of handwritten getters
- [ ] Project compiles cleanly after running `mvn clean install`

### Before you start :red_circle:

:point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down::point_down::point_down::point_down::point_down::point_down::point_down:
Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first. Pay special attention to the ECA agreement section and the requirement to sign-off your commit.

#### Kubernetes

If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.

- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)

#### OpenShift

If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.

Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

### PR DESCRIPTION
**Pull request by rohit-satya**
## Description

Remove getter methods and use Lombok `@Getter` annotation in HelmConfig.HelmType
Fixes #2930

## Type of change

 - [x] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.dev/jkube/contributing)
 - [x] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [x] My code follows the style guidelines of this project
 - [x] I Keep It Small and Simple: The smaller the PR is, the easier it is to review and have it merged
 - [x] I use [conventional commits](https://www.conventionalcommits.org/) in my commit messages
 - [x] I have performed a self-review of my code
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [x] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I have added tests that prove my fix is effective or that my feature works
 - [ ] New and existing unit tests pass locally with my changes
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by manusa** [comment]
### Eclipse JKube [CI Report](https://github.com/eclipse-jkube/ci)

Started new GH workflow run for https://github.com/eclipse-jkube/jkube/pull/3071 (_2024-05-17T10:31:02Z_)

:gear: [JKube E2E Tests (9126835602)](https://github.com/eclipse-jkube/ci/actions/runs/9126835602) :hourglass_flowing_sand:
- :hourglass_flowing_sand: [Bootstrap CI test run (#3071)](https://github.com/eclipse-jkube/ci/actions/runs/9126835602/job/25095887166)

**Review by manusa — APPROVED** [review]
LGTM, thx!

**Comment by rohanKanojia** [comment]
@rohit-satya : This issue is already assigned to someone else. 

Please ask on the issue first whether the assignee is still working on it before directly creating pull request.

**Comment by rohit-satya** [comment]
@rohanKanojia I noticed that the issue has been assigned for a month now and I understand that this issue is a simple one. Going forward, I will keep in mind and raise a PR post the issue being assigned to me

**Comment by manusa** [comment]
Please, add a comment on the issue so that we can reassign.

**Pull request merged**
