### PR TITLE
Update OpenShiftHelmLintTaskTest.java

### LINKED ISSUE #2966: OpenShiftHelmLintTaskTest Remove unused imports
### Description

The class [OpenShiftHelmLintTaskTest](https://github.com/eclipse-jkube/jkube/blob/64cf840e05754fc742aeb3aee7107dedb4542b6d/gradle-plugin/openshift/src/test/java/org/eclipse/jkube/gradle/plugin/task/OpenShiftHelmLintTaskTest.java) has unused imports.

The following lines:
https://github.com/eclipse-jkube/jkube/blob/64cf840e05754fc742aeb3aee7107dedb4542b6d/gradle-plugin/openshift/src/test/java/org/eclipse/jkube/gradle/plugin/task/OpenShiftHelmLintTaskTest.java#L25

- [x] should be removed

### Before you start :red_circle:

:point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down::point_down::point_down::point_down::point_down::point_down::point_down:
Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first. Pay special attention to the ECA agreement section and the requirement to sign-off your commit.

#### Kubernetes

If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.

- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)

#### OpenShift

If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.

Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

### PR DESCRIPTION
**Pull request by kushagrasinha123ks**
## Description
Fixes #2966 

Removed the unused import statement `import java.io.IOException;` from the `OpenShiftHelmLintTaskTest.java` file.

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Chore (non-breaking change which doesn't affect codebase;
  test, version modification, documentation, etc.)

## Checklist
- [x] I have read the [contributing guidelines](https://www.eclipse.dev/jkube/contributing)
- [x] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
- [x] My code follows the style guidelines of this project
- [x] I Keep It Small and Simple: The smaller the PR is, the easier it is to review and have it merged
- [x] I use [conventional commits](https://www.conventionalcommits.org/) in my commit messages
- [x] I have performed a self-review of my code
- [ ] I Added [CHANGELOG](../CHANGELOG.md) entry
- [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
- [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I tested my code in Kubernetes
- [ ] I tested my code in OpenShift

git config user.name "Kushagra Sinha"
git config user.email "kushagrasinha123ks@gmail.com"
git commit --amend --signoff
git push origin kushagra/issue#2966 -f

### CODE REVIEW

**Comment by manusa** [comment]
### Eclipse JKube [CI Report](https://github.com/eclipse-jkube/ci)

Started new GH workflow run for https://github.com/eclipse-jkube/jkube/pull/2977 (_2024-04-25T07:24:02Z_)

:gear: [JKube E2E Tests (8828612735)](https://github.com/eclipse-jkube/ci/actions/runs/8828612735) :hourglass_flowing_sand:
- :hourglass_flowing_sand: [Bootstrap CI test run (#2977)](https://github.com/eclipse-jkube/ci/actions/runs/8828612735/job/24237922055)

**Comment by rohanKanojia** [comment]
@kushagrasinha123ks  Welcome, Thanks a lot for contributing to Eclipse JKube :+1:,

In order to contribute to Eclipse, you would need to create an [Eclipse Account](https://accounts.eclipse.org/) and Sign [Eclipse Contributor Agreement](https://accounts.eclipse.org/user/login?destination=user/eca). Once you've created an eclipse account you would need to update your commit message with a `Signed-off-by:` footer. You can do it like this:
```
# (Optional): Configure Git User and Email
git config user.name "Your Name"
git config user.email "your_email@example.com"

# Amend your previous commit with signed off footer
git commit --amend --signoff

# push changes again
git push origin yourbranchname -f
```

**Comment by kushagrasinha123ks** [comment]
> @kushagrasinha123ks Welcome, Thanks a lot for contributing to Eclipse JKube 👍,
> 
> In order to contribute to Eclipse, you would need to create an [Eclipse Account](https://accounts.eclipse.org/) and Sign [Eclipse Contributor Agreement](https://accounts.eclipse.org/user/login?destination=user/eca). Once you've created an eclipse account you would need to update your commit message with a `Signed-off-by:` footer. You can do it like this:
> 
> ```
> # (Optional): Configure Git User and Email
> git config user.name "Your Name"
> git config user.email "your_email@example.com"
> 
> # Amend your previous commit with signed off footer
> git commit --amend --signoff
> 
> # push changes again
> git push origin yourbranchname -f
> ```



> @kushagrasinha123ks Welcome, Thanks a lot for contributing to Eclipse JKube 👍,
> 
> In order to contribute to Eclipse, you would need to create an [Eclipse Account](https://accounts.eclipse.org/) and Sign [Eclipse Contributor Agreement](https://accounts.eclipse.org/user/login?destination=user/eca). Once you've created an eclipse account you would need to update your commit message with a `Signed-off-by:` footer. You can do it like this:
> 
> ```
> # (Optional): Configure Git User and Email
> git config user.name "Your Name"
> git config user.email "your_email@example.com"
> 
> # Amend your previous commit with signed off footer
> git commit --amend --signoff
> 
> # push changes again
> git push origin yourbranchname -f
> ```

**Review by manusa — APPROVED** [review]
LGTM, thx!

**Review by rohanKanojia — APPROVED** [review]

**Pull request merged**
