### PR TITLE
Removed mockito usage from test file

### PR DESCRIPTION
**Pull request by bgayatri3**
## Description

Fixes # (issue)

## Type of change

 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [ ] I have read the [contributing guidelines](https://www.eclipse.dev/jkube/contributing)
 - [ ] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [ ] My code follows the style guidelines of this project
 - [ ] I Keep It Small and Simple: The smaller the PR is, the easier it is to review and have it merged
 - [ ] I use [conventional commits](https://www.conventionalcommits.org/) in my commit messages
 - [ ] I have performed a self-review of my code
 - [ ] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [ ] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [ ] I have added tests that prove my fix is effective or that my feature works
 - [ ] New and existing unit tests pass locally with my changes
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by manusa** [comment]
### Eclipse JKube [CI Report](https://github.com/eclipse-jkube/ci)

Started new GH workflow run for https://github.com/eclipse-jkube/jkube/pull/3425 (_2024-10-03T17:36:53Z_)

:gear: [JKube E2E Tests (11166853707)](https://github.com/eclipse-jkube/ci/actions/runs/11166853707) :hourglass_flowing_sand:
- :hourglass_flowing_sand: [Bootstrap CI test run (#3425)](https://github.com/eclipse-jkube/ci/actions/runs/11166853707/job/31041736661)

**Comment by rohanKanojia** [comment]
@bgayatri3 : Hello, https://github.com/eclipse-jkube/jkube/issues/3405 is already assigned to someone else. Usually you should get the issue assigned to you before working on it.

**Comment by rohanKanojia** [comment]
@bgayatri3 : Could you please address my comment on https://github.com/eclipse-jkube/jkube/pull/3419 so that we can merge it?

Unfortunately, until you sign Eclipse Contributor Agreement, we would not able to merge your changes (Legal requirements).

**Comment by rohanKanojia** [comment]
@bgayatri3 : polite ping, are you still working on this task?

**Pull request closed without merging**
