### PR TITLE
fix: don't unconditionally add latest tag

### PR DESCRIPTION
**Pull request by ecausarano**
## Description

Tag `latest` should not be added when image name contains pattern `%t`, or it will likely break immutable repositories that don't allow overwriting artifact tags.

Fixes https://github.com/eclipse-jkube/jkube/issues/3161

## Type of change
 - [X] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [ ] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [X] I have read the [contributing guidelines](https://www.eclipse.dev/jkube/contributing)
 - [X] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [X] My code follows the style guidelines of this project
 - [X] I Keep It Small and Simple: The smaller the PR is, the easier it is to review and have it merged
 - [X] I use [conventional commits](https://www.conventionalcommits.org/) in my commit messages
 - [X] I have performed a self-review of my code
 - [X] I Added [CHANGELOG](../CHANGELOG.md) entry
 - [ ] I have updated the [documentation](../kubernetes-maven-plugin/doc) accordingly
 - [X] No new bugs, code smells, etc. in [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube) report
 - [X] I have added tests that prove my fix is effective or that my feature works
 - [X] New and existing unit tests pass locally with my changes
 - [ ] I tested my code in Kubernetes
 - [ ] I tested my code in OpenShift

### CODE REVIEW

**Comment by manusa** [comment]
### Eclipse JKube [CI Report](https://github.com/eclipse-jkube/ci)

Started new GH workflow run for https://github.com/eclipse-jkube/jkube/pull/3163 (_2024-06-13T08:37:35Z_)

:gear: [JKube E2E Tests (9496448182)](https://github.com/eclipse-jkube/ci/actions/runs/9496448182) :hourglass_flowing_sand:
- :hourglass_flowing_sand: [Bootstrap CI test run (#3163)](https://github.com/eclipse-jkube/ci/actions/runs/9496448182/job/26170869479)

**Comment by rohanKanojia** [comment]
@ecausarano : Thanks a lot for contributing to Eclipse JKube :+1:,

In order to contribute to Eclipse, you would need to create an [Eclipse Account](https://accounts.eclipse.org/) and Sign [Eclipse Contributor Agreement](https://accounts.eclipse.org/user/login?destination=user/eca). Once you've created an eclipse account you would need to update your commit message with a `Signed-off-by:` footer. You can do it like this:
```
# (Optional): Configure Git User and Email
git config user.name "Your Name"
git config user.email "your_email@example.com"

# Amend your previous commit with signed off footer
git commit --amend --signoff

# push changes again
git push origin yourbranchname -f
```

**Comment by rohanKanojia** [comment]
@ecausarano : Could you please address [code smell](https://sonarcloud.io/project/issues?resolved=false&sinceLeakPeriod=true&pullRequest=3163&id=jkubeio_jkube&open=AZAQ4oGugZpUyKKVB9Om) pointed by Sonar analysis?

**Comment by rohanKanojia** [comment]
We probably would want to get rid of this logic if it's redundant. I'll add a commit on top of this pull request once I verify it's not getting used anywhere.

**Comment by rohanKanojia** [comment]
I tested with various combinations of image name placeholders, in almost all cases image name generated seems to be a valid container image. 

|  Image Name | Generated Image | Result |
------------------------|---------------------------|----------------------------------------------------------|
| %a/%a:%a | `jkube-helm-maven/jkube-helm-maven:jkube-helm-maven` | :heavy_check_mark:  |
|%g/%g:%g | `demos/demos:demos` | :heavy_check_mark: |
|%v/%v:%v | Throws exception in case of SNAPSHOT project | Works for stable version, throws exception for SNAPSHOT version |
|%t/%t:%t | `snapshot-240613-100209-0678/snapshot-240613-100209-0678:snapshot-240613-100209-0678` | :heavy_check_mark: |
|%l/%l:%l | latest/latest:latest | :heavy_check_mark: |
|%v in tag | `rohankanojia/demos:1.0.0-SNAPSHOT` | :heavy_check_mark: |
|%l in tag | `rohankanojia/demos:latest` | :heavy_check_mark: |
|%t in tag | `rohankanojia/demos:snapshot-240613-100209-0678` | :heavy_check_mark: |

**Comment by ecausarano** [comment]
I have the feeling there's a disconnect between the core plugin and the call in the JIB extension that pushes to the registry. I had to add `-Djkube.generator.name=%g/%a:%t` to make it work.

**Comment by manusa** [comment]
> I have the feeling there's a disconnect between the core plugin and the call in the JIB extension that pushes to the registry. I had to add `-Djkube.generator.name=%g/%a:%t` to make it work.

I understand that this is unrelated to this PR or the original issue and that it should be treated as a separate issue/problem, right?

**Review by manusa — APPROVED** [review]
LGTM, thx!

**Pull request merged**
