### PR TITLE
chore: tidy up setup test method signature

### LINKED ISSUE #2749: PortForwardServiceTest.setUp The declared Exception exception is never thrown
### Description

The method [PortForwardServiceTest.setUp](https://github.com/eclipse-jkube/jkube/blob/108f6ed341bbc4760b7e6b8497ea28004945fc58/jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/PortForwardServiceTest.java#L54) declares an Exception that is never thrown.

The following line
https://github.com/eclipse-jkube/jkube/blob/108f6ed341bbc4760b7e6b8497ea28004945fc58/jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/PortForwardServiceTest.java#L54

- [x] should be changed to:

```java
    void setUp() {
```

### Before you start :red_circle:

:point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down::point_down::point_down::point_down::point_down::point_down::point_down:
Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first. Pay special attention to the ECA agreement section and the requirement to sign-off your commit.

#### Kubernetes

If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.

- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)

#### OpenShift

If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.

Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

### PR DESCRIPTION
**Pull request by lcardito**
## Description

Tidy up setup test method signature.

Fixes #2749

## Type of change
 - [ ] Bug fix (non-breaking change which fixes an issue)
 - [ ] Feature (non-breaking change which adds functionality)
 - [ ] Breaking change (fix or feature that would cause existing functionality to change
 - [x] Chore (non-breaking change which doesn't affect codebase;
   test, version modification, documentation, etc.)

## Checklist
 - [x] I have read the [contributing guidelines](https://www.eclipse.dev/jkube/contributing)
 - [x] I signed-off my commit with a user that has signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php)
 - [x] My code follows the style guidelines of this project
 - [x] I Keep It Small and Simple: The smaller the PR is, the easier it is to review and have it merged
 - [x] I use [conventional commits](https://www.conventionalcommits.org/) in my commit messages
 - [x] I have performed a self-review of my code
 - [x] New and existing unit tests pass locally with my changes
 - [x] I tested my code in Kubernetes

### CODE REVIEW

**Comment by manusa** [comment]
### Eclipse JKube [CI Report](https://github.com/eclipse-jkube/ci)

Started new GH workflow run for https://github.com/eclipse-jkube/jkube/pull/3331 (_2024-08-21T14:57:16Z_)

:gear: [JKube E2E Tests (10492298153)](https://github.com/eclipse-jkube/ci/actions/runs/10492298153) :hourglass_flowing_sand:
- :hourglass_flowing_sand: [Bootstrap CI test run (#3331)](https://github.com/eclipse-jkube/ci/actions/runs/10492298153/job/29063474826)

**Comment by rohanKanojia** [comment]
@lcardito : Could you please rebase your branch against latest `master` branch? I think this dependencies check failure got fixed already.

**Comment by lcardito** [comment]
Hey @rohanKanojia - there might be something that I am missing but I think this is up-to-date?

```
❯ git remote -v
origin  git@github.com:lcardito/jkube.git (fetch)
origin  git@github.com:lcardito/jkube.git (push)
upstream        git@github.com:eclipse-jkube/jkube.git (fetch)
upstream        git@github.com:eclipse-jkube/jkube.git (push)
❯ git fetch upstream
❯ git rebase upstream/master
Current branch chore/port_forwarding_service_test is up to date.
```

**Comment by rohanKanojia** [comment]
@lcardito : Oh, you're right . We had fixed a similar failure in https://github.com/eclipse-jkube/jkube/issues/3284 . Seems like we're facing a different issue.

**Review by rohanKanojia — APPROVED** [review]

**Review by manusa — APPROVED** [review]
LGTM, thx!

**Pull request merged**
