### PR TITLE
Modified DebugService.java in jkube submodule

### LINKED ISSUE #3470: DebugService : Unused import `import org.eclipse.jkube.kit.config.image.build.JKubeBuildStrategy;`
### Component

JKube Kit

### Description

The class [DebugService](https://github.com/eclipse-jkube/jkube/blob/master/jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/DebugService.java#L32) presents the issue: 
The following line:
https://github.com/eclipse-jkube/jkube/blob/78e8631c9c101e52dc94f14fb97c16383396afc5/jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/DebugService.java#L32
should be removed.

### :red_circle: Before you start :red_circle:

:point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down:

Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first.

Pay special attention to the ECA agreement section and the requirement to sign-off your commit.

This is a [first-timers-only](https://eclipse.dev/jkube/contributing/#first-timers-only-issues) issue. These issues are especially created for contributors who are contributing to the project for the **first time**.

If you have already contributed to this project in the past, please don't ask to be assigned one of these issues and look for [good-first-issues](https://github.com/eclipse-jkube/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22) or [help-wanted](https://github.com/eclipse-jkube/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22help+wanted%22+) issues instead in order to continue you contributor journey in the project.

### PR DESCRIPTION
**Pull request by Kishorecoder96**
Fix #3470 

made changes in import packages

### CODE REVIEW

**Comment by manusa** [comment]
### Eclipse JKube [CI Report](https://github.com/eclipse-jkube/ci)

Started new GH workflow run for https://github.com/eclipse-jkube/jkube/pull/3505 (_2024-11-01T16:33:26Z_)

:gear: [JKube E2E Tests (11632796114)](https://github.com/eclipse-jkube/ci/actions/runs/11632796114) :hourglass_flowing_sand:
- :hourglass_flowing_sand: [Bootstrap CI test run (#3505)](https://github.com/eclipse-jkube/ci/actions/runs/11632796114/job/32396649311)

**Comment by rohanKanojia** [comment]
@Kishorecoder96 Welcome, Thanks a lot for contributing to Eclipse JKube :+1:,

In order to contribute to Eclipse, you would need to create an [Eclipse Account](https://accounts.eclipse.org/) and Sign [Eclipse Contributor Agreement](https://accounts.eclipse.org/user/login?destination=user/eca). Once you've created an eclipse account you would need to update your commit message with a `Signed-off-by:` footer. You can do it like this:
```
# (Optional): Configure Git User and Email
git config user.name "Your Name"
git config user.email "your_email@example.com"

# Amend your previous commit with signed off footer
git commit --amend --signoff

# push changes again
git push origin yourbranchname -f
```

**Comment by Kishorecoder96** [comment]
i made changes can you check now?

**Review by rohanKanojia — APPROVED** [review]

**Review by manusa — APPROVED** [review]
LGTM, thx!

**Pull request merged**
